CREATE TABLE IF NOT EXISTS ds_schema_migrations (version INT PRIMARY KEY, applied_utc TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS ds_accounts (account_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY, label VARCHAR(120) NOT NULL, enabled TINYINT NOT NULL DEFAULT 1, created_utc TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ds_tokens (token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY, account_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, label VARCHAR(120) NOT NULL, revoked TINYINT NOT NULL DEFAULT 0, created_utc TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (account_id) REFERENCES ds_accounts(account_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ds_participants (account_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, participant_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, name_snapshot VARCHAR(120) NULL, metadata_json JSON NULL, PRIMARY KEY(account_id, participant_id), FOREIGN KEY(account_id) REFERENCES ds_accounts(account_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ds_sessions (account_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, session_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, participant_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL, manifest_json JSON NOT NULL, updated_utc TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY(account_id, session_id), FOREIGN KEY(account_id) REFERENCES ds_accounts(account_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ds_uploads (upload_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY, account_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, session_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, file_name VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, expected_bytes BIGINT UNSIGNED NOT NULL, sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, encoding VARCHAR(16) NOT NULL DEFAULT 'identity', original_bytes BIGINT UNSIGNED NULL, original_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL, status VARCHAR(16) NOT NULL DEFAULT 'pending', storage_key VARCHAR(180) CHARACTER SET ascii COLLATE ascii_bin NULL, created_utc TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, verified_utc DATETIME NULL, UNIQUE KEY file_revision(account_id, session_id, file_name, sha256), FOREIGN KEY(account_id, session_id) REFERENCES ds_sessions(account_id, session_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ds_events (account_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, session_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, event_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, event_type VARCHAR(64) NOT NULL, event_utc DATETIME(6) NULL, entered_utc DATETIME(6) NULL, payload_json JSON NOT NULL, source_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, PRIMARY KEY(account_id, session_id, event_id, source_sha256), FOREIGN KEY(account_id, session_id) REFERENCES ds_sessions(account_id, session_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO ds_schema_migrations(version) VALUES(1);

INSERT IGNORE INTO ds_schema_migrations(version) VALUES(2);
